module.exports = {
  lightweightMarkup: require("./lightweightMarkup"),
  html: require("./html"),
  ebook: require("./ebook"),
  documentation: require("./documentation"),
  roff: require("./roff"),
  tex: require("./tex"),
  xml: require("./xml"),
  outline: require("./outline"),
  wordProcessor: require("./wordProcessor"),
  interactiveNotebook: require("./interactiveNotebook"),
  pageLayout: require("./pageLayout"),
  wikiMarkup: require("./wikiMarkup"),
  slideShow: require("./slideShow"),
  pdf: require("./pdf"),
}
